spring:
  profiles:
    active: dev
---
server:
  port: 8088
spring:
  profiles: prod
  application:
    name: config-single-client
  cloud:
    config:
      config: http://localhost:6061
      label: master
      profile: prod
---
server:
  port: 8087
spring:
  profiles: dev
  application:
    name: config-single-client
  cloud:
    config:
      config: http://localhost:6061
      label: master
      profile: dev




